### ISSUE TITLE
Can't see sitemap.xml

### ISSUE THREAD

**Issue by karwalbubble** [wilr/silverstripe-googlesitemaps#116]
Is there any reason I can't see sitemap.xml on my project root. I tried to search for adding sitemap.xml to project, always taking me to add-ons(this and others), unable to find any forum so thought should post it here. 
Can anyone help me to setup custom sitemap.xml if I don't want to use any add-on or module? Or is this the requirement for sitemap.xml setup? If I setup this module, am I able to customize it to add more pages or so?

**Comment by wilr** [comment]
Hi!

sitemap.xml is not a file, it is a registered route which points to the controller (https://github.com/wilr/silverstripe-googlesitemaps/blob/master/_config/routes.yml).

If you want to customize the sitemap.xml contents please see the README file.

All the best!

**Comment by karwalbubble** [comment]
@wilr , thanks for reply. However can I customize it if I don't want to use this module?

**Comment by wilr** [comment]
If you don't want to use this module please uninstall this module and define the file manually. If you have a sitemap.xml file I'm pretty sure it will use that rather than the module anyway. If you are trying to do a customisation that the module doesn't support please let me know so we can add support for it!

**Comment by karwalbubble** [comment]
@wilr , Thank you for explanation. Currently I cannot use this module because I need custom sitemap which includes sitetree as well as other links. I will definitely let you know if I will use this module in future. 
I know my query is not related to this module but trying to find out solution from devs like you. I was wondering if someone can help me to setup link sitemap.xml in silverstripe as I cannot go to this link(www.website.com/sitemap.xml) and it is redirecting to predefined sitemap admin page. I couldn't see any redirection in place for this link in code so was thinking if it is a default behavior of silverstripe or not. I have already sent this request to silverstripe(meanwhile trying to find solution from forums).

**Comment by wilr** [comment]
If you want to add other non sitetree links use `GoogleSitemap::register_routes()`

``
GoogleSitemap::register_routes(array(
    'some-url',
    'another-link.com'
));```

https://github.com/wilr/silverstripe-googlesitemaps/blob/master/docs/en/index.md

**Comment by exp0sure74** [comment]
@wilr 
Being a beginner I have still problems figuring out where to put/call GoogleSitemap::register_routes.
It works in the _config.php but that's not where I need it. I have a page type that renders DataObjects as pages with an action. Ideally I'd call the function after looping my DataObjects from the action function  but that didn't work (not showing up in sitemap.xml).

**Comment by wilr** [comment]
@exp0sure74 please use the SilverStripe Slack for support questions like this in future. In your case I think you should use `register_dataobject` See https://github.com/wilr/silverstripe-googlesitemaps/blob/master/docs/en/index.md#including-dataobjects

**Comment by exp0sure74** [comment]
Ok, will use Slack in the future.
I ended up putting it into the DataObject itself but I might still have to create other custom routes at some point. Also it might be more efficient to generate all routes with 1 query and php loop instead of have the sitemap class doing a single query for each DataObject. At least that's what I understand is happening now. Maybe an issue for large databases, maybe I'm wrong.
